name: CI

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.22'

            - name: Build
              run: go build ./cmd/fe

            - name: Run tests with coverage
              run: go test ./... -coverprofile=coverage.out

            - name: Generate coverage badge
              uses: ncruces/go-coverage-badge@latest
              with:
                outout: coverage.svg
